apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ollama
spec:
  chart:
    spec:
      chart: ollama
      sourceRef:
        kind: HelmRepository
        name: ollama
      version: '0.57.0'
  interval: 5m0s

  values:
    ollama:
      gpu:
        enabled: true
      models:
      - llava